name: macOS Workflow with NGROK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, macos]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Установка Homebrew (если не установлен)
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $GITHUB_ENV
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Установка NGROK
        run: brew install --cask ngrok

      - name: Настройка NGROK
        run: ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Запуск локального сервиса
        run: |
          # Пример: запуск простого HTTP-сервера на порту 8000
          python3 -m http.server 8000 &
          SERVER_PID=$!

          # Запуск NGROK для туннелирования порта 8000
          ngrok http 8000 --log=stdout > ngrok.log &
          NGROK_PID=$!

          # Ожидание установления туннеля
          sleep 10

          # Получение публичного URL
          PUBLIC_URL=$(grep -o "https://[0-9a-z]*\.ngrok.io" ngrok.log | head -n1)
          echo "Public URL: $PUBLIC_URL"

          # Сохранение URL как артефакт или вывод для использования далее
          echo "::set-output name=ngrok_url::$PUBLIC_URL"

      # Дополнительные шаги по необходимости

      - name: Завершение процессов
        if: always()
        run: |
          kill $SERVER_PID
          kill $NGROK_PID
