name: Setup macOS with VNC Access via Ngrok

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-macos:
    name: Setup macOS with VNC
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Homebrew
        run: |
          echo | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Install Ngrok and Utilities
        run: |
          brew install ngrok
          brew install screenresolution

      - name: Create new user for VNC (optional)
        run: |
          sudo sysadminctl -addUser vncuser -fullName "VNC User" -password "YourStrongPassword"
          sudo dscl . -append /Groups/admin GroupMembership vncuser

      - name: Enable Remote Management (VNC) and configure access
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
          -activate -configure -access -on -users vncuser -privs -all \
          -restart -agent -menu

      - name: Set VNC password (use your desired password)
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
          -configure -clientopts -setvnclegacy -vnclegacy yes -setvncpw -vncpw "YourStrongPassword"

      - name: Set screen resolution to avoid black screen
        run: |
          sudo screenresolution set 1280x1024x32

      - name: Ensure graphical session is active
        run: |
          sudo launchctl load /System/Library/LaunchDaemons/com.apple.WindowServer.plist
          sudo launchctl load /System/Library/LaunchDaemons/com.apple.loginwindow.plist
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
          -activate -restart -agent -menu

      - name: Start ngrok on port 5900 for VNC
        run: |
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          nohup ngrok tcp 5900 &

      - name: Wait for ngrok to start
        run: |
          sleep 20

      - name: Get ngrok public URL
        run: |
          curl --silent http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      - name: Keep the workflow running (sleep)
        run: |
          echo "VNC is now accessible. Keeping the workflow alive..."
          sleep 9999999
