name: Setup macOS VNC Server with ngrok

on:
  workflow_dispatch:

jobs:
  vnc-server:
    runs-on: macos-latest
    timeout-minutes: 360  # Таймаут на 6 часов

    steps:
    - name: Проверить текущего пользователя
      run: whoami

    - name: Включить совместное использование экрана с VNC Legacy Mode
      env:
        VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
      run: |
        # Проверка длины пароля
        if [ ${#VNC_PASSWORD} -gt 8 ]; then
          echo "Пароль VNC должен содержать максимум 8 символов."
          exit 1
        fi
        # Конвертация пароля в шестнадцатеричный формат
        HEX_PW=$(echo -n "$VNC_PASSWORD" | xxd -p | tr -d '\n')
        # Настройка VNC-сервера с использованием Legacy Mode
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
          -activate \
          -configure \
          -access -on \
          -users "runner" \
          -privs -all \
          -clientopts -setvnclegacy yes \
          -clientopts -setvncpw "$HEX_PW" \
          -restart -agent -console

    - name: Установить ngrok
      run: |
        brew install --cask ngrok

    - name: Настроить ngrok
      run: |
        mkdir -p ~/.ngrok2
        cat <<EOF > ~/.ngrok2/ngrok.yml
        version: "2"
        authtoken: "${{ secrets.NGROK_AUTH_TOKEN }}"
        tunnels:
          vnc:
            proto: tcp
            addr: 5900
        EOF

    - name: Запустить туннель ngrok для VNC
      id: ngrok
      run: |
        # Запуск ngrok в фоновом режиме
        nohup ngrok start vnc --config ~/.ngrok2/ngrok.yml > ngrok.log 2>&1 &
        sleep 15
        # Извлечение публичного адреса
        PUBLIC_URL=$(grep -o "tcp://[0-9\.]*\.tcp.ngrok.io:[0-9]*" ngrok.log | head -n1)
        if [ -z "$PUBLIC_URL" ]; then
          echo "Не удалось получить публичный адрес ngrok."
          exit 1
        fi
        HOST=$(echo $PUBLIC_URL | cut -d':' -f2 | tr -d '/')
        PORT=$(echo $PUBLIC_URL | cut -d':' -f3)
        echo "host=$HOST" >> $GITHUB_OUTPUT
        echo "port=$PORT" >> $GITHUB_OUTPUT

    - name: Показать адрес для подключения
      run: |
        echo "VNC доступен по адресу: ${{ steps.ngrok.outputs.host }}:${{ steps.ngrok.outputs.port }}"
        echo "Логин: runner"
        echo "Пароль: ${{ secrets.VNC_PASSWORD }}"

    - name: Поддерживать работу Runner до 6 часов
      run: |
        echo "Сеанс VNC активен. Он будет закрыт через 6 часов."
        sleep 21600  # 6 часов в секундах
