name: Cl

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Шаг 1: Проверка кода (опционально, если нужно)
      - name: Checkout Code
        uses: actions/checkout@v3

      # Шаг 2: Скачивание ngrok для macOS
      - name: Download ngrok
        run: |
          curl -L https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-arm64.zip -o ngrok.zip
          unzip ngrok.zip
          chmod +x ngrok
          sudo mv ngrok /usr/local/bin/ngrok

      # Шаг 3: Аутентификация ngrok с использованием токена
      - name: Authenticate ngrok
        run: ngrok config add-authtoken $NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      # Шаг 4: Установка RustDesk через Homebrew
      - name: Install RustDesk
        run: |
          brew install --cask rustdesk

      # Шаг 5: Запуск RustDesk (если требуется автоматизация)
      - name: Start RustDesk
        run: |
          open /Applications/RustDesk.app
          # Дополнительно: Настройка RustDesk, если необходима автоматическая конфигурация

      # Шаг 6: Создание туннеля ngrok для RustDesk
      # Предполагается, что RustDesk использует определенные порты. Убедитесь, какие порты необходимо открывать.
      - name: Create ngrok Tunnel for RustDesk
        run: |
          ngrok tcp 21115 &  # Замените 21115 на фактический порт RustDesk, если отличается
          sleep 5  # Ждем немного, чтобы ngrok установил соединение

      # Шаг 7: Получение и вывод публичного URL туннеля ngrok
      - name: Get ngrok Public URL
        run: |
          curl --silent --show-error http://localhost:4040/api/tunnels | \
          python3 -c "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])" > ngrok_url.txt
          cat ngrok_url.txt

      # (Опционально) Шаг 8: Сохранение URL как артефакта или переменной окружения для дальнейшего использования
      - name: Save ngrok URL as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ngrok-url
          path: ngrok_url.txt
