name: Setup macOS with RustDesk

on: 
  push:
    branches:
      - main

jobs:
  macos-setup:
    runs-on: macos-latest

    steps:
    # Шаг 1: Проверка кода
    - name: Checkout repository
      uses: actions/checkout@v3

    # Шаг 2: Установка RustDesk
    - name: Install RustDesk
      run: |
        brew install --cask rustdesk

    # Шаг 3: Запуск RustDesk
    - name: Start RustDesk
      run: |
        rustdesk &

    # Шаг 4: Получение информации для подключения
    - name: Fetch RustDesk connection details
      run: |
        echo "RustDesk is running. Fetching connection details..."
        sleep 5 # Подождем, пока RustDesk запустится
        RUSTDESK_ID=$(cat ~/Library/Preferences/com.rustdesk.RustDesk.plist | grep -A 1 UniqueID | tail -n 1 | cut -d'<' -f3 | cut -d'>' -f2)
        RUSTDESK_PASS=$(cat ~/Library/Preferences/com.rustdesk.RustDesk.plist | grep -A 1 Password | tail -n 1 | cut -d'<' -f3 | cut -d'>' -f2)
        echo "RustDesk ID: $RUSTDESK_ID"
        echo "RustDesk Password: $RUSTDESK_PASS"

    # Шаг 5: Вывод данных для подключения
    - name: Output connection info
      run: |
        echo "=============================="
        echo "RustDesk ID: $RUSTDESK_ID"
        echo "RustDesk Password: $RUSTDESK_PASS"
        echo "=============================="
