name: Setup macOS with RDP Access via Ngrok

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-macos:
    name: Setup macOS with RDP
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      
      - name: Install necessary packages (ngrok, RDP)
        run: |
          brew install --cask ngrok
          brew install xquartz
          brew install --cask microsoft-remote-desktop

      - name: Set up ngrok for RDP
        run: |
          # Установите свой токен от ngrok
          ngrok authtoken <2XtaZMz7tK1jlXohnotOWy0MAAs_2ZFSnvf31hSEBRtz4ZQuG>
          ngrok tcp 3389 &

      - name: Get ngrok public URL
        run: |
          sleep 10
          curl --silent http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      - name: Install and configure RDP
        run: |
          # Установка и настройка RDP
          brew install xrdp
          sudo xrdp --nodaemon
          sudo /usr/sbin/xrdp -nodaemon

      - name: Display login instructions
        run: |
          echo "RDP is set up. Use the ngrok URL with port 3389 to connect."

      - name: Display ngrok status
        run: |
          ngrok status
