name: Setup macOS with VNC Access via Ngrok

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-macos:
    name: Setup macOS with VNC
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Ngrok
        run: |
          brew install ngrok

      - name: Enable Remote Management (VNC)
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
          -activate -configure -access -on -users $USER -privs -all \
          -restart -agent -menu

      - name: Set VNC password
        run: |
          echo "YourVNCPassword" | sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
          -configure -clientopts -setvnclegacy -vnclegacy yes -setvncpw

      - name: Start ngrok on port 5900 for VNC
        run: |
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          nohup ngrok tcp 5900 &

      - name: Wait for ngrok to start
        run: |
          sleep 10

      - name: Get ngrok public URL
        run: |
          curl --silent http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      - name: Keep the workflow running (sleep)
        run: |
          echo "VNC is now accessible. Keeping the workflow alive..."
          sleep 9999999
