name: Setup macOS with RustDesk

on:
  push:
    branches:
      - main

jobs:
  macos-setup:
    runs-on: macos-latest

    steps:
    # Шаг 1: Клонирование репозитория
    - name: Checkout repository
      uses: actions/checkout@v3

    # Шаг 2: Установка необходимых инструментов (например, brew)
    - name: Install Homebrew and dependencies
      run: |
        yes "" | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || true
        brew install --cask rustdesk

    # Шаг 3: Запуск RustDesk и сохранение ID и пароля
    - name: Launch RustDesk and generate connection info
      run: |
        echo "Запуск RustDesk..."
        open -a RustDesk
        sleep 10  # Ждем 10 секунд для инициализации RustDesk

        # Пытаемся получить ID и пароль через plist-файл
        RUSTDESK_PLIST="$HOME/Library/Preferences/com.rustdesk.RustDesk.plist"
        if [ -f "$RUSTDESK_PLIST" ]; then
          RUSTDESK_ID=$(defaults read com.rustdesk.RustDesk UniqueID)
          RUSTDESK_PASS=$(defaults read com.rustdesk.RustDesk Password)
          echo "RustDesk ID: $RUSTDESK_ID"
          echo "RustDesk Password: $RUSTDESK_PASS"
        else
          echo "Не удалось найти plist-файл RustDesk. Возможно, приложение не инициализировалось."
        fi

    # Шаг 4: Вывод информации для подключения
    - name: Output connection info
      run: |
        echo "=============================="
        echo "RustDesk ID: $RUSTDESK_ID"
        echo "RustDesk Password: $RUSTDESK_PASS"
        echo "=============================="
