name: Setup macOS with RustDesk

on: 
  push:
    branches:
      - main

jobs:
  macos-setup:
    runs-on: macos-latest

    steps:
    # Шаг 1: Проверка кода
    - name: Checkout repository
      uses: actions/checkout@v3

    # Шаг 2: Установка RustDesk
    - name: Install RustDesk
      run: |
        brew install --cask rustdesk

    # Шаг 3: Запуск RustDesk в фоновом режиме
    - name: Start RustDesk
      run: |
        nohup rustdesk > rustdesk.log 2>&1 &

    # Шаг 4: Ожидание для завершения запуска RustDesk
    - name: Wait for RustDesk to start
      run: |
        echo "Waiting for RustDesk to start..."
        sleep 20 # Увеличьте время, если необходимо

    # Шаг 5: Проверка наличия конфигурационного файла
    - name: Check RustDesk configuration
      run: |
        echo "Checking for RustDesk config file..."
        ls ~/Library/Preferences/com.rustdesk.RustDesk.plist || echo "Config file not found!"

    # Шаг 6: Извлечение ID и пароля для подключения через RustDesk
    - name: Fetch RustDesk connection details
      shell: bash
      run: |
        echo "Fetching RustDesk connection details..."
        RUSTDESK_ID=$(defaults read com.rustdesk.RustDesk UniqueID 2>/dev/null)
        RUSTDESK_PASS=$(defaults read com.rustdesk.RustDesk Password 2>/dev/null)
        if [ -z "$RUSTDESK_ID" ] || [ -z "$RUSTDESK_PASS" ]; then
          echo "Error: Could not retrieve RustDesk ID or Password."
          exit 1
        fi
        echo "RustDesk ID: $RUSTDESK_ID"
        echo "RustDesk Password: $RUSTDESK_PASS"

    # Шаг 7: Вывод данных для подключения
    - name: Output connection info
      run: |
        echo "=============================="
        echo "RustDesk ID: $RUSTDESK_ID"
        echo "RustDesk Password: $RUSTDESK_PASS"
        echo "=============================="
