name: Setup macOS VNC with ngrok

on:
  workflow_dispatch:

jobs:
  setup-vnc:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $GITHUB_ENV
        eval "$(/opt/homebrew/bin/brew shellenv)"

    - name: Install VNC Server and jq
      run: |
        brew install tigervnc jq

    - name: Set VNC password
      env:
        VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
      run: |
        mkdir -p ~/.vnc
        echo "$VNC_PASSWORD" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd

    - name: Start VNC Server
      run: |
        vncserver :1 -geometry 1280x800 -depth 24
      env:
        DISPLAY: ":1"

    - name: Install ngrok
      run: |
        brew install --cask ngrok

    - name: Authenticate ngrok
      run: |
        ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start ngrok tunnel
      id: ngrok
      run: |
        ngrok tcp 5901 &
        sleep 10
        TUNNEL_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        echo "TUNNEL_URL=$TUNNEL_URL" >> $GITHUB_ENV

    - name: Display Tunnel URL
      run: |
        echo "VNC Tunnel URL: ${{ env.TUNNEL_URL }}"

    - name: Keep job running
      run: |
        sleep 3600
