name: Setup macOS VNC Server with ngrok

on:
  workflow_dispatch:

jobs:
  vnc-server:
    runs-on: macos-latest
    timeout-minutes: 360  # Таймаут на 6 часов

    steps:
    - name: Проверить текущего пользователя
      run: whoami

    - name: Включить совместное использование экрана
      run: |
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
          -activate \
          -configure -access -on \
          -users "$USER" \
          -privs -all

    - name: Установить пароль для VNC
      run: |
        # Фиксированный пароль VNC (максимум 8 символов)
        VNC_PASSWORD="SecureP@ss"
        HEX_PW=$(echo -n "$VNC_PASSWORD" | xxd -p | tr -d '\n')
        sudo defaults write /Library/Preferences/com.apple.RemoteManagement VNCPassword "$HEX_PW"
        sudo defaults write /Library/Preferences/com.apple.RemoteManagement VNCAlwaysStartOnConsole -bool true
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent -console

    - name: Установить ngrok
      run: |
        brew install --cask ngrok

    - name: Настроить ngrok
      run: |
        mkdir -p ~/.ngrok2
        cat <<EOF > ~/.ngrok2/ngrok.yml
        version: "2"
        authtoken: "YOUR_NGROK_AUTH_TOKEN"
        tunnels:
          vnc:
            proto: tcp
            addr: 5900
        EOF

    - name: Запустить туннель ngrok для VNC
      id: ngrok
      run: |
        ngrok start vnc --config ~/.ngrok2/ngrok.yml > ngrok.log &
        sleep 15
        # Извлечь публичный адрес
        PUBLIC_URL=$(grep -o "tcp://[0-9\.]*\.tcp.ngrok.io:[0-9]*" ngrok.log | head -n1)
        HOST=$(echo $PUBLIC_URL | cut -d':' -f2 | tr -d '/')
        PORT=$(echo $PUBLIC_URL | cut -d':' -f3)
        echo "host=$HOST" >> $GITHUB_OUTPUT
        echo "port=$PORT" >> $GITHUB_OUTPUT

    - name: Показать адрес для подключения
      run: |
        echo "VNC доступен по адресу: ${{ steps.ngrok.outputs.host }}:${{ steps.ngrok.outputs.port }}"
        echo "Логин: runner"  # Стандартный пользователь GitHub Actions на macOS
        echo "Пароль: SecureP@ss"

    - name: Поддерживать работу Runner до 6 часов
      run: |
        echo "Сеанс VNC активен. Он будет закрыт через 6 часов."
        sleep 21600  # 6 часов в секундах
